// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendReply(arg1) {
  return window['go']['ussdgateway']['Gateway']['SendReply'](arg1);
}
