// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ussdgateway} from '../models';

export function SendReply(arg1:ussdgateway.ReplyRequest):Promise<ussdgateway.ReplyResponse>;
